sudo: required
language: node_js
node_js:
  - 8

matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    env: CC=clang CXX=clang++ npm_config_clang=1 MARKTEXT_IS_OFFICIAL_RELEASE=1 MARKTEXT_EXIT_ON_ERROR=1
    compiler: clang
  - os: linux
    dist: trusty
    env: CC=clang CXX=clang++ npm_config_clang=1 MARKTEXT_IS_OFFICIAL_RELEASE=1 MARKTEXT_EXIT_ON_ERROR=1 DISPLAY=:99.0
    compiler: clang

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xvfb
    # atom/keyboard-layout
    - libx11-dev
    - libxkbfile-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 && sleep 3 ; fi

  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe

  - $CC --version
  - $CXX --version
  - npm --version
  - yarn --version

  - yarn

script:
  - yarn run lint
  - yarn run test_xvfb

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run release:linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run release:mac ; fi

  # calculate checksums
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-*-x64.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-*-x86_64.AppImage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 build/Mark\ Text-*-mac.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 build/Mark\ Text-*.dmg ; fi

branches:
  only:
  - master
  - /^release-v[0-9.]+$/
